apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: socket-server
  name: socket-server
spec:
  selector:
    matchLabels:
      app: socket-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: socket-server
    spec:
      containers:
      - image: theresistancecontainer.azurecr.io/theresistanceonlinesocketserver:latest
        name: socket-server
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
        env:
          - name: ResistanceDb
            value: "Server=tcp:resistanceonline.database.windows.net,1433;Database=resistanceDb;Authentication=Active Directory Default"
          - name: SecurityKey
            value: "fVqtLvM5P@JSBa863@VX"
          - name: ValidIssuer
            value: "TheResistanceAPI"
          - name: ValidAudience
            value: ”https://theresistanceboardgameonline.com”
          - name: ExpiryInMinutes
            value: "5760" 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: socket-server-service
  labels:
    run: socket-server-service
spec:
  ports:
  - port: 80
  selector:
    app: socket-server
  type: ClusterIP