apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: socket-server
  name: socket-server
spec:
  selector:
    matchLabels:
      app: socket-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: socket-server
    spec:
      containers:
      - image: theresistancecontainer.azurecr.io/theresistanceonlinesocketserver:latest
        name: socket-server
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
        env:
          - name: AppConfigurationConnection
            value: "https://theresistanceconfiguration.azconfig.io"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: socket-server-service
  labels:
    run: socket-server-service
spec:
  ports:
  - port: 80
  selector:
    app: socket-server
  type: ClusterIP