name: Build Web And Socket Server, Push To ACR, Restart AKS
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  AZURE_CONTAINER_REGISTRY: "theresistancecontainer"
  CONTAINER_NAME: "theresistanceonlineweb"
  RESOURCE_GROUP: "rsg-theresistance"
  CLUSTER_NAME: "theresistancecluster"
  
jobs:
  build:
    name: Build TheResistanceOnline.Web
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Build the Docker image and Push
      id: build-image
      run: |
        az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} --file TheResistanceOnline.Web/Dockerfile .
