
name: Build and Push Container Images to Container Registry, Restart Kubernetes Cluster

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "theresistancecontainer"
  THERESISTANCEONLINE_WEB_CONTAINER_NAME: "theresistanceonlineweb"
  THERESISTANCEONLINE_SOCKETSERVER_CONTAINER_NAME: "theresistanceonlinesocketserver"
  RESOURCE_GROUP: "rsg-theresistance"
  CLUSTER_NAME: "theresistancecluster"
  DEPLOYMENT_MANIFEST_PATH_WEB_APP: "scripts/theresistanceonline-app.yaml"
  DEPLOYMENT_MANIFEST_PATH_SOCKET_SERVER: "scripts/theresistanceonline-socketServer.yaml"


jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    #needs: [buildImage] put back when re put the one before TTTTTOOOOODOOOOOOOO
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      # Deploys application based on given manifest file
      - name: Deploys Web App
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'ingress-basic'
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH_WEB_APP }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.THERESISTANCEONLINE_WEB_CONTAINER_NAME }}:latest
      # Deploys application based on given manifest file
      - name: Deploys Socket Server
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'ingress-basic'
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH_SOCKET_SERVER }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.THERESISTANCEONLINE_SOCKETSERVER_CONTAINER_NAME }}:latest


