
name: Build and Push Container Images to Container Registry, Restart Kubernetes Cluster

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "theresistancecontainer"
  THERESISTANCEONLINE.WEB_CONTAINER_NAME: "theresistanceonlineweb"
  THERESISTANCEONLINE.SOCKETSERVER_CONTAINER_NAME: "theresistanceonlinesocketserver"
  RESOURCE_GROUP: "rsg-theresistance"
  CLUSTER_NAME: "theresistancecluster"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build the TheResistanceOnline.Web image and Push to theresistanceonlineweb container repo
        id: build-TheResistanceOnline_Web-And-Push
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.THERESISTANCEONLINE.WEB_CONTAINER_NAME }}:latest --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} --file TheResistanceOnline.Web/Dockerfile .
          
      - name: Build the TheResistanceOnline.SocketServer image and Push to theresistanceonlinesocketserver container repo
        id: build-TheResistanceOnline_SocketServer-And-Push
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.THERESISTANCEONLINE.SOCKETSERVER_CONTAINER_NAME }}:latest --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} --file TheResistanceOnline.SocketServer/Dockerfile .
